# Setup deck for Travis-CI

language: python
python:
    - "2.7_with_system_site_packages"

notifications:
    email:
        #- suave-developers@lists.stanford.edu
  
branches:
    only:
        - master
        - develop
        - feature-vsp_travis

before_install:
    - sudo apt-get update
    - sudo apt-get install -qq python-numpy python-scipy python-matplotlib python-scikits-learn python-pip
    - sudo apt-get install git git-gui cmake libxml2-dev libfltk1.3-dev g++ libcpptest-dev libjpeg-dev libglm-dev libeigen3-dev libcminpack-dev libglew-dev 
    - mkdir OpenVSP
    - cd OpenVSP
    - mkdir repo
    - git clone https://github.com/OpenVSP/OpenVSP.git repo
    - mkdir build buildlibs
    - cd buildlibs
    - cmake -DCMAKE_BUILD_TYPE=Release -DVSP_USE_SYSTEM_FLTK=false -DVSP_USE_SYSTEM_CPPTEST=false -DVSP_USE_SYSTEM_LIBXML2=true -DVSP_USE_SYSTEM_EIGEN=false -DVSP_USE_SYSTEM_FLTK=false -DVSP_USE_SYSTEM_GLM=true -DVSP_USE_SYSTEM_GLEW=true -DVSP_USE_SYSTEM_CMINPACK=true ../repo/Libraries -DCMAKE_BUILD_TYPE=Release
    - make -j8
    - cd ../build
    - cmake ../repo/src/ -DVSP_LIBRARY_PATH=/home/travis/build/suavecode/SUAVE/OpenVSP/buildlibs -DCMAKE_BUILD_TYPE=Release
    - make -j8
    - ls
    - cd python_api
    - ls
    - pwd
    - python vsp.py
    - export PATH=$PATH:/home/travis/build/suavecode/SUAVE/OpenVSP/build/python_api
    - cd ..
  
install:
    - cd ../../trunk
    - python setup.py develop
    - cd ../regression
    - pip install coveralls
  
# run test
script:  
     coverage run --source=SUAVE --omit=../trunk/SUAVE/Plugins/pint/* automatic_regression.py test
    
after_success:
  coveralls
