# Setup deck for Travis-CI

language: python
python:
    - "3.6"

notifications:
    email:
        - suave-developers@lists.stanford.edu
  
branches:
    only:
        - master
        - develop

before_install:
    - sudo apt-get update
    - sudo apt-get install -qq python3-pip
  
install:
    - cd trunk
    - pip3 install --upgrade pip
    - pip3 install numpy
    - pip3 install scipy
    - pip3 install scikit-learn
    - pip3 install matplotlib
    - pip3 install coveralls
    - python3 setup.py develop
    - cd ../regression
  
# run test
script:  
     coverage run --source=SUAVE --omit=../trunk/SUAVE/Plugins/pint/* automatic_regression.py test
    
after_success:
  coveralls
