# Setup deck for Travis-CI

language: python
python:
  - "2.7_with_system_site_packages"

branches:
  only:
    - master

before_install:
    - sudo apt-get update
  
install:
    # dependencies
    - pip install numpy
    - pip install scipy
    - pip install matplotlib
    # suave
    - cd trunk
    - python setup.py install
    - cd ../scripts
  
# run test
script:  
    - python automatic_regression.py