# Setup deck for Travis-CI

language: python
python:
    - "3.6"

notifications:
    email:
        - suave-developers@lists.stanford.edu
  
branches:
    only:
        - master
        - develop

before_install:
    - sudo apt-get update
    - sudo apt-get install -qq python-numpy python-scipy python-matplotlib python-scikits-learn python-pip
  
install:
    - cd trunk
    - python setup.py develop
    - cd ../regression
    - pip install coveralls
  
# run test
script:  
     coverage run --source=SUAVE --omit=../trunk/SUAVE/Plugins/pint/* automatic_regression.py test
    
after_success:
  coveralls
