# Setup deck for Travis-CI

language: python
python:
    - "2.7_with_system_site_packages"

notifications:
    email:
      #  - suave-developers@lists.stanford.edu
        - ebotero@stanford.edu
  
branches:
    only:
        - master
        - develop
        - feature-test_coveralls 

before_install:
    - sudo apt-get update
    - sudo apt-get install -qq python-numpy python-scipy python-matplotlib python-scikits-learn python-pip
  
install:
    - cd trunk
    - python setup.py install
    - cd ../regression
    - pip install coveralls
  
# run test
script:  
     coverage run --source=suave automatic_regression.py test
    
after_success:
  coveralls
